#!/usr/bin/env python
import os
import sys
from jupyterhub.orm import new_session_factory, User
db_file='/srv/jupyterhub_db/jupyterhub.sqlite'
db = new_session_factory('sqlite:///' + db_file)()

if len(sys.argv) != 2:
	print("Usage: {} USERNAME".format(sys.argv[0]))
	sys.exit(1)
else:
	username = sys.argv[1]

try:
	user = db.query(User).filter(User.name == username)[0]
except:
	print("Could not find user {} in ORM.".format(username))
	sys.exit(1)

if 'container_id' in user.state:
	del(user.state['container_id'])
	print("Deleted container_id from {}'s user.state.".format(username))
else:
	print("No container_id in {}'s user.state.".format(username))
