#!/bin/bash

node-info | egrep -v '^Containers|^Total' | egrep 'Containers|Memory'  | \
	sed '$!N;s/\n/ /' | 
	while read line ; do
		mu=$(echo $line | awk '{print $7}')
		expr \( 14 - $mu \) / 2
	done | 
	awk '{ s+=$1 } END { print s }'
